# Generated by Django 4.1.5 on 2023-01-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('alternativa1', models.TextField()),
                ('alternativa2', models.TextField(null=True)),
                ('alternativa3', models.TextField(null=True)),
                ('alternativa4', models.TextField(null=True)),
                ('alternativa5', models.TextField(null=True)),
                ('resposta', models.IntegerField()),
                ('nivel_dificuldade', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('data_questao_inserida', models.DateTimeField(verbose_name='Inserida')),
                ('assunto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assunto')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(null=True)),
                ('like', models.IntegerField(default=0)),
                ('questao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questao')),
            ],
        ),
        migrations.AddField(
            model_name='assunto',
            name='disciplina_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disciplina'),
        ),
    ]
