# Generated by Django 4.1.5 on 2023-01-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='questao',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='alternativa_verdadeira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questao',
            name='disciplina',
            field=models.ManyToManyField(to='main.disciplina'),
        ),
    ]
