# Generated by Django 4.1.5 on 2023-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='data_questao_inserida',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
